### ISSUE TITLE
Update DPDK version

### ISSUE THREAD

**Issue by twood02** [sdnfv/onvm-dpdk#1]
@nks5295 @phil-lopreiato 

Sometime soon we should upgrade to a newer version of DPDK.  I think in this case we may not need to modify the library---version 16.04 fixed the issue we used to have for mutli-process hash tables:
 
> **hash: Fixed hash library to support multi-process mode.**
> Fix hash library to support multi-process mode, using a jump table, instead of storing a function pointer to the key compare function. Multi-process mode only works with the built-in compare functions, however a custom compare function (not in the jump table) can only be used in single-process mode.

http://dpdk.readthedocs.io/en/latest/rel_notes/release_16_04.html#libraries

Do we modify the library for any other reasons?

**Comment by phil-lopreiato** [comment]
This is on my winter break list.

This is the diff of our fork: https://github.com/sdnfv/onvm-dpdk/compare/onvm

It doesn't look like we have a modification in the library for multiprocess hash tables, although we have a few other minor things.

**Comment by twood02** [comment]
All the stuff in the last file - cuckoo hash is the multi process fix I
think.

The rest just looks like examples.

Let's just test if onvm works with a new vanilla dpdk

**Comment by phil-lopreiato** [comment]
I've pushed a [new branch](https://github.com/sdnfv/onvm-dpdk/tree/16.11-update) that updates our dpdk version to the current latest, v16.11. It includes 4 commits:
 - Reverts f72231677e91dff16ef47dc7f7686272e607243d. This undoes the changes we made to support the hash library in multiprocess mode (see above). 
 - Merges in [v16.04](http://dpdk.org/doc/guides/rel_notes/release_16_04.html)
 - Merges in [v16.07](http://dpdk.org/doc/guides/rel_notes/release_16_07.html)
 - Merges in [v16.11](http://dpdk.org/doc/guides/rel_notes/release_16_11.html)

So let's test out onvm using this branch, and if it works, we can land the update. I've already verified that onvm builds, which is a good first step.

**Comment by nks5295** [comment]
Sweet, awesome! I can do some testing when I clean up and test the tcp NF today

**Comment by twood02** [comment]
to be clear---can this branch be considered "vanilla" DPDK 16.11 with no changes?

**Comment by phil-lopreiato** [comment]
Yes, this branch is "vanilla" DPDK 16.11

```
$ git log --oneline v16.11..16.11-update 
0a94ec5 Merge tag 'v16.11' into 16.11-update
b94a77e Merge tag 'v16.07' into 16.11-update
335431a Merge tag 'v16.04' into 16.11-update
98fcdb4 Revert "Patch rte_cuckoo_hash"
f722316 Patch rte_cuckoo_hash
697187c Merge tag 'v2.2.0' into onvm
3f2d0aa Add .gitignore file
5e98419 Adding client_server_mp which uses one port
```
